# Generated by Django 5.2.7 on 2025-11-05 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Maya', 'Maya'), ('Bank Transfer', 'Bank Transfer')], max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('processed_by_admin', models.BooleanField(default=False)),
            ],
        ),
    ]
