# Generated by Django 5.2.7 on 2025-11-11 13:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_alter_member_options_and_more'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_days', models.IntegerField(help_text='Duration in days (e.g., 30 for monthly, 90 for quarterly)', unique=True)),
                ('duration_label', models.CharField(help_text='Display label (e.g., "1 Month", "3 Months")', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this duration', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Pricing',
                'verbose_name_plural': 'Membership Pricing',
                'ordering': ['duration_days'],
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.RemoveField(
            model_name='payment',
            name='processed_by_admin',
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Reference number for GCash, Maya, or Bank Transfer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stored_member_id',
            field=models.CharField(db_index=True, default='UNKNOWN', help_text='Member ID at time of payment', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='stored_member_name',
            field=models.CharField(default='Unknown Member', help_text='Member name at time of payment', max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, db_column='member_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='memberships.member'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Maya', 'Maya'), ('GTyme', 'GTyme'), ('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='processed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Failed', 'Failed'), ('Refunded', 'Refunded')], default='Completed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stored_member_id'], name='payments_pa_stored__b2bcee_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='payments_pa_payment_1d6e55_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'),
        ),
    ]
