# Generated by Django 5.2.7 on 2025-11-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_membershippricing_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Maya', 'Maya'), ('GoTyme', 'GoTyme'), ('Bank Transfer', 'Bank Transfer'), ('PayPal', 'PayPal'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], default='Cash', max_length=50),
        ),
    ]
