# Generated by Django 5.2.7 on 2025-11-11 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='membership_plan',
            field=models.ForeignKey(blank=True, help_text='The pricing plan purchased', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.membershippricing'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stored_duration_days',
            field=models.IntegerField(default=0, help_text='Duration in days at time of payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='stored_plan_label',
            field=models.CharField(default='Unknown Plan', help_text='Plan label at time of payment', max_length=50),
        ),
    ]
