# Generated by Django 5.2.7 on 2025-11-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_membership_plan_payment_stored_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershippricing',
            name='duration_days',
            field=models.IntegerField(help_text='Duration in days (e.g., 30 for monthly, 90 for quarterly)'),
        ),
    ]
