# Generated by Django 5.2.7 on 2025-11-11 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_membershipplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
    ]
