# Generated by Django 5.2.7 on 2025-11-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_membershipplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='name',
            field=models.CharField(blank=True, help_text='Full name of the staff member', max_length=255),
        ),
    ]
