# Generated by Django 5.2.7 on 2025-11-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('memberships', '0005_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dashboardstats',
            index=models.Index(fields=['date'], name='dashboard_d_date_891865_idx'),
        ),
        migrations.AddIndex(
            model_name='gymcheckin',
            index=models.Index(fields=['date'], name='dashboard_g_date_c0a98d_idx'),
        ),
        migrations.AddIndex(
            model_name='gymcheckin',
            index=models.Index(fields=['member', 'date'], name='dashboard_g_member__30aff9_idx'),
        ),
    ]
