# Generated by Django 5.2.7 on 2025-11-05 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(help_text='The staff/owner who created this member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipconfig',
            name='modified_by',
            field=models.ForeignKey(limit_choices_to={'role': 'Owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_modifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
