# Generated by Django 5.2.7 on 2025-11-10 16:14

import memberships.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_member_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=memberships.models.member_photo_path),
        ),
    ]
