# Generated by Django 5.2.7 on 2025-11-10 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_alter_member_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='membershipconfig',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='member',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_id'], name='memberships_member__c85b18_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='memberships_is_acti_0e3831_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['end_date'], name='memberships_end_dat_94c933_idx'),
        ),
    ]
