# Generated by Django 5.2.7 on 2025-11-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_transactions', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
