# Generated by Django 5.2.7 on 2025-11-11 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentsummary',
            options={'ordering': ['-month'], 'verbose_name': 'Payment Summary', 'verbose_name_plural': 'Payment Summaries'},
        ),
        migrations.AlterField(
            model_name='paymentsummary',
            name='month',
            field=models.DateField(help_text='First day of the month', unique=True),
        ),
        migrations.AddIndex(
            model_name='paymentsummary',
            index=models.Index(fields=['month'], name='metrics_pay_month_96145d_idx'),
        ),
    ]
