from django.contrib import admin
from .models import PaymentSummary

@admin.register(PaymentSummary)
class PaymentSummaryAdmin(admin.ModelAdmin):
    list_display = ('month', 'total_income', 'total_transactions', 'generated_at')
    list_filter = ('month',)
    date_hierarchy = 'month'
    ordering = ('-month',)
    readonly_fields = ('month', 'total_income', 'total_transactions', 'generated_at')
    
    def has_add_permission(self, request):
        # Prevent manual creation - should be generated by system
        return False

