from django.contrib import admin
from .models import PaymentSummary, ActiveMemberSnapshot

@admin.register(PaymentSummary)
class PaymentSummaryAdmin(admin.ModelAdmin):
    list_display = ('month', 'total_income', 'total_transactions', 'generated_at')
    list_filter = ('month',)
    date_hierarchy = 'month'
    ordering = ('-month',)
    readonly_fields = ('month', 'total_income', 'total_transactions', 'generated_at')
    
    def has_add_permission(self, request):
        # Prevent manual creation - should be generated by system
        return False


@admin.register(ActiveMemberSnapshot)
class ActiveMemberSnapshotAdmin(admin.ModelAdmin):
    list_display = (
        'date', 
        'active_count', 
        'total_members', 
        'new_members_today', 
        'expired_today',
        'total_revenue_today',
        'check_ins_today',
        'created_at'
    )
    list_filter = ('date',)
    date_hierarchy = 'date'
    ordering = ('-date',)
    readonly_fields = (
        'date', 
        'active_count', 
        'total_members', 
        'new_members_today', 
        'expired_today',
        'total_revenue_today',
        'check_ins_today',
        'created_at'
    )
    
    def has_add_permission(self, request):
        # Prevent manual creation - should be generated by management command
        return False
